package cn.myweather;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-21T14:57:18.819+08:00
 * Generated source version: 3.2.1
 * 
 */
@WebService(targetNamespace = "http://ldk.sanlen.com/", name = "WeatherInterfaceImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface WeatherInterfaceImpl {

    @WebMethod
    @RequestWrapper(localName = "queryWeather", targetNamespace = "http://ldk.sanlen.com/", className = "cn.myweather.QueryWeather")
    @ResponseWrapper(localName = "queryWeatherResponse", targetNamespace = "http://ldk.sanlen.com/", className = "cn.myweather.QueryWeatherResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String queryWeather(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
